### ISSUE TITLE
JsReport 'playground' web crash at startup

### ISSUE THREAD

**Issue by anonimoaveces** [jsreport/jsreport-mongodb-store#2]
Hi, I've installed the module jsreport-mongodb-store and setup with these values on prod.config.json:

```
"connectionString": { 
    "name": "mongodb", 
    "port": 27017,
    "address": "127.0.0.1", 
    "databaseName" : "jsreports"
},
"blobStorage": "gridFS",
```

The server runs fine, but when I try to open in a navigator:

https://localhost

App crashes throwing:

2016-01-28T12:34:57.838Z - error: Error when processing OData GET: /odata/settin
gs?_=1453984496994&studio=normal TypeError: Cannot read property 'then' of undef
ined
    at ODataServer.<anonymous> (C:<zzzzzz\jsreport\
node_modules\jsreport-mongodb-store\lib\mongoProvider.js:55:58)
    at ODataServer.executeQuery (C:\zzzzzz\jsreport
\node_modules\jsreport\node_modules\jsreport-express\node_modules\simple-odata-s
erver\lib\odataServer.js:136:14)
    at module.exports (C:\zzzzzz\jsreport\node_modu
les\jsreport\node_modules\jsreport-express\node_modules\simple-odata-server\lib\
query.js:57:9)

I tested jsreports database and this exist and have the collections:

data
settings
system.indexes
templates

with data.

My specs are:

jsreport@0.11.0
jsreport-mongodb-store@0.3.0

P.S. I had to install mongodb in jsreport main directory, because the require of jsreport-mongodb-store module it didn't found it.

Any help?

**Comment by pofider** [comment]
Thank you for full issue description.

Unfortunately jsreport-mongodb-store@0.3.0 only works with jsreport@0.12.0.

Please reinstall jsreport-mongodb-store@0.1.\* and it should work.

**Comment by anonimoaveces** [comment]
Thanks!

**Comment by sanshrestha21** [comment]
Hi, i have installed postgres-store v3.0.0 , everything working fine but while running command jsreport start , throws error Error when processing OData

**Comment by sanshrestha21** [comment]
[devops@localhost jsreport02]$ node server.js 
2022-01-19T05:52:14.307Z - info: Initializing jsreport (version: 3.3.0, configuration file: jsreport.config.json, nodejs: 16.11.1)
2022-01-19T05:52:14.309Z - info: Searching for available extensions in /home/devops/jsreport02/
2022-01-19T05:52:14.314Z - info: Extensions location cache /tmp/jsreport/core/locations.json contains older information, crawling
2022-01-19T05:52:14.515Z - info: Found 36 extension(s)
2022-01-19T05:52:14.528Z - debug: Writing extension locations cache to /tmp/jsreport/core/locations.json
2022-01-19T05:52:14.529Z - debug: Discovered 36 extensions
2022-01-19T05:52:14.573Z - debug: Extension authentication@3.2.0 is disabled, skipping
2022-01-19T05:52:14.574Z - info: Using extension base@3.0.0
2022-01-19T05:52:14.580Z - info: Using extension child-templates@3.0.1
2022-01-19T05:52:14.588Z - info: Using extension cli@3.0.0
2022-01-19T05:52:14.593Z - info: Using extension components@3.2.0
2022-01-19T05:52:14.595Z - info: Using extension data@3.0.1
2022-01-19T05:52:14.596Z - info: Using extension express@3.2.1
2022-01-19T05:52:14.750Z - info: Using extension freeze@3.0.1
2022-01-19T05:52:14.751Z - info: Using extension fs-store@3.0.0
2022-01-19T05:52:14.793Z - info: Using extension handlebars@3.0.0
2022-01-19T05:52:14.795Z - info: Using extension import-export@3.0.2
2022-01-19T05:52:14.803Z - info: Using extension jsrender@3.0.0
2022-01-19T05:52:14.810Z - info: Using extension licensing@3.0.1
2022-01-19T05:52:14.821Z - info: Using extension localization@3.1.1
2022-01-19T05:52:14.822Z - info: Using extension npm@3.1.0
2022-01-19T05:52:14.824Z - info: Using extension pdf-utils@3.2.0
2022-01-19T05:52:14.826Z - info: Using extension postgres-store@3.0.0
2022-01-19T05:52:14.914Z - info: Using extension reports@3.0.1
2022-01-19T05:52:14.916Z - info: Using extension tags@3.1.0
2022-01-19T05:52:14.917Z - info: Using extension text@3.0.0
2022-01-19T05:52:14.918Z - info: Using extension version-control@3.0.1
2022-01-19T05:52:14.927Z - info: Using extension assets@3.2.0
2022-01-19T05:52:14.933Z - info: Using extension authorization@3.2.0
2022-01-19T05:52:14.935Z - debug: Extension authorization@3.2.0 was disabled
2022-01-19T05:52:14.935Z - info: Using extension browser-client@3.1.0
2022-01-19T05:52:14.937Z - info: Using extension chrome-pdf@3.1.0
2022-01-19T05:52:14.939Z - debug: Chrome strategy is chrome-pool, numberOfWorkers: 1
2022-01-19T05:52:14.939Z - debug: Chrome custom launch options are args=--no-sandbox, executablePath=/opt/google/chrome-unstable/chrome
2022-01-19T05:52:14.940Z - info: Using extension docx@3.1.0
2022-01-19T05:52:14.941Z - info: Using extension html-to-xlsx@3.1.0
2022-01-19T05:52:14.984Z - info: html-to-xlsx detected chrome as available html engine
2022-01-19T05:52:14.984Z - info: Using extension pptx@3.1.0
2022-01-19T05:52:14.985Z - info: Using extension scheduling@3.0.1
2022-01-19T05:52:15.019Z - info: Using extension scripts@3.2.0
2022-01-19T05:52:15.019Z - info: Using extension static-pdf@3.0.0
2022-01-19T05:52:15.020Z - info: Using extension studio@3.3.0
2022-01-19T05:52:15.081Z - info: Using extension xlsx@3.1.0
2022-01-19T05:52:15.095Z - info: Using extension public-templates@3.0.0
2022-01-19T05:52:15.096Z - debug: Extension public-templates@3.0.0 was disabled
2022-01-19T05:52:15.096Z - info: Using extension sample-template@3.1.0
2022-01-19T05:52:15.097Z - info: Using extension studio-theme-dark@3.0.1
2022-01-19T05:52:15.098Z - info: Using general timeout for rendering (reportTimeout: 60000)
2022-01-19T05:52:15.098Z - info: Using postgres provider for template store.
2022-01-19T05:52:15.149Z - debug: studio default theme is: light
2022-01-19T05:52:15.161Z - info: Creating default express app.
2022-01-19T05:52:15.175Z - info: jsreport server successfully started on http port: 5488
2022-01-19T05:52:15.176Z - info: Verifying license key free
2022-01-19T05:52:15.178Z - info: Using free license
2022-01-19T05:52:15.184Z - debug: Creating samples is disabled
2022-01-19T05:52:15.184Z - info: Initializing worker threads
2022-01-19T05:52:15.184Z - debug: Extensions in workers: base, child-templates, components, data, express, handlebars, jsrender, localization, npm, pdf-utils, reports, text, version-control, assets, browser-client, chrome-pdf, docx, html-to-xlsx, pptx, scripts, static-pdf, studio, xlsx
2022-01-19T05:52:15.373Z - info: 2 worker threads initialized in 189ms
2022-01-19T05:52:15.373Z - info: Starting temp files cleanup with 180000ms threshold
2022-01-19T05:52:15.374Z - info: reporter initialized
2022-01-19T05:52:33.320Z - debug: OData query on templates
2022-01-19T05:52:33.326Z - debug: OData query on components
2022-01-19T05:52:33.329Z - debug: OData query on data
2022-01-19T05:52:33.331Z - debug: OData query on folders
2022-01-19T05:52:33.332Z - debug: OData query on tags
2022-01-19T05:52:33.339Z - debug: OData query on assets
2022-01-19T05:52:33.340Z - error: Error when processing OData GET: /odata/assets?$select=isSharedHelper,scope,name,shortid,tags,folder&$orderby=name TypeError: Cannot read properties of undefined (reading 'forEach')
    at module.exports (/home/devops/jsreport02/node_modules/@jsreport/odata-to-sql/lib/query.js:54:28)
    at Object.query (/home/devops/jsreport02/node_modules/@jsreport/odata-to-sql/lib/transformer.js:46:14)
    at Cursor.toArray (/home/devops/jsreport02/node_modules/@jsreport/sql-store/lib/sqlProvider.js:22:29)
    at replay (/home/devops/jsreport02/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:51:21)
    at /home/devops/jsreport02/node_modules/@jsreport/jsreport-core/lib/main/store/collection.js:58:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-19T05:52:33.349Z - debug: OData query on scripts
2022-01-19T05:52:33.354Z - debug: OData query on schedules
2022-01-19T05:52:33.358Z - debug: OData query on settings
2022-01-19T05:52:35.437Z - debug: OData query on templates
2022-01-19T05:52:35.441Z - debug: OData query on folders
2022-01-19T05:52:35.443Z - debug: OData query on components
2022-01-19T05:52:35.447Z - debug: OData query on data
2022-01-19T05:52:35.449Z - debug: OData query on tags
2022-01-19T05:52:35.451Z - debug: OData query on assets
2022-01-19T05:52:35.452Z - error: Error when processing OData GET: /odata/assets?$select=isSharedHelper,scope,name,shortid,tags,folder&$orderby=name TypeError: Cannot read properties of undefined (reading 'forEach')
