### ISSUE TITLE
Error when loading extension jsreport-contrib-mongodb

### ISSUE THREAD

**Issue by jagdeep-anetcorp** [jsreport/jsreport-mongodb-store#7]
error: Error when loading extension jsreport-contrib-mongodb
TypeError: Cannot read property 'push' of undefined
    at Object.module.exports (F:\node\jsreportapps\node_modules\jsreport-contrib-mongodb\lib\mongo.js:8:44)
    at Object._useOne (F:\node\jsreportapps\node_modules\jsreport-core\lib\extensions\extensionsManager.js:174:75)
    at Object._useMany (F:\node\jsreportapps\node_modules\jsreport-core\lib\extensions\extensionsManager.js:87:20)
    at <anonymous>
2018-08-22T07:14:50.241Z - error: Error occured during reporter init Error: Error when loading extension jsreport-contrib-mongodb
TypeError: Cannot read property 'push' of undefined

**Comment by jagdeep-anetcorp** [comment]
for fixing this issue, I added a check in mongo.js

if (reporter['scripts'].allowedModules !== '*' && typeof reporter['scripts'].allowedModules !== 'undefined' && reporter['scripts'].allowedModules ) {
}

**Comment by pofider** [comment]
I think you are in a wrong repository here.
This is `jsreport-mongodb-store` not `jsreport-contrib-mongodb`.

We don't maintain the [jsreport-contrib-mongodb](https://github.com/jsreport/jsreport-contrib-mongodb) as it stays in the readme.
